services:
  slurmctld: # submitter
    build: 
      context: .
      dockerfile: services/slurm.Dockerfile
    networks:
      - cluster
      - virtual_machine

  # node:
  #   build: 
  #     context: .
  #     dockerfile: services/slurm.Dockerfile
  #   depends_on:
  #     - slurmctld
  #   networks:
  #     - cluster

  # mongo:
  #   image: mongo 
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=openbox
  #     - MONGO_INITDB_ROOT_PASSWORD=openbox
  #     - MONGO_INITDB_DATABASE=openbox
  #   networks:
  #     - virtual_machine
  #
  # openbox:
  #   build: # TODO
  #     context: .
  #     dockerfile: services/open-box.Dockerfile
  #   depends_on:
  #     - mongo
  #   networks:
  #     - virtual_machine
  #
  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: orchestrator
  #     POSTGRES_PASSWORD: orchestrator
  #   networks:
  #     - virtual_machine
  #
  # orchestrator:
  #   build:
  #     context: .
  #     dockerfile: services/orchestrator.Dockerfile
  #
  #   depends_on:
  #     - postgres
  #     - openbox
  #     - slurmctld
  #   networks:
  #     - virtual_machine
  #     - cluster

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /home/cicio/projects/openbox-on-slurm/
  var_lib_mysql:
  var_log_slurm:
  pg_migrations:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: /home/cicio/projects/openbox-on-slurm/
  shared_volume:

networks:
  cluster:
    driver: bridge
  virtual_machine:
    driver: bridge

  # mariadb:
  #   image: mariadb:10.11
  #   networks:
  #     - cluster
  #
  # slurmdbd:
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - cluster
    # depends_on:
    #   - slurmdbd
